# Generated by Django 4.2.4 on 2024-06-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminName', models.TextField(max_length=100)),
                ('adminPassword', models.TextField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('custPassword', models.TextField(max_length=128)),
                ('custName', models.TextField(max_length=100)),
                ('custTelNo', models.CharField(max_length=15)),
                ('custAdd', models.TextField(max_length=128)),
                ('custDateReg', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('docName', models.TextField(max_length=100)),
                ('docPassword', models.TextField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('petImg', models.ImageField(blank=True, null=True, upload_to='petImage/')),
                ('petName', models.TextField(max_length=100)),
                ('petNeuterDate', models.DateField(blank=True, null=True)),
                ('petVaccinationDate', models.DateField(blank=True, null=True)),
                ('petServiceName', models.TextField(max_length=100, null=True)),
                ('petServiceDateReceived', models.DateField(blank=True, null=True)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrative.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staffName', models.TextField(max_length=100)),
                ('staffPassword', models.TextField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petServiceName', models.TextField(max_length=100, null=True)),
                ('petServiceDateReceived', models.DateField(blank=True, null=True)),
                ('docId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrative.doctor')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrative.pet')),
            ],
        ),
        migrations.CreateModel(
            name='CustInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrative.customer')),
                ('docId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrative.doctor')),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_info', to='Administrative.pet')),
                ('petServiceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to='Administrative.pet')),
            ],
        ),
    ]
