# Generated by Django 4.2.4 on 2024-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('adminId1', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminName1', models.TextField(max_length=100)),
                ('adminPassword1', models.TextField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
