# Generated by Django 4.2.4 on 2024-06-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative', '0002_admin1_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin1',
            new_name='Admin',
        ),
    ]
