# Generated by Django 4.2.4 on 2024-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative', '0003_rename_admin1_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='adminId1',
            new_name='adminId',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminName1',
            new_name='adminName',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminPassword1',
            new_name='adminPassword',
        ),
    ]
