# Generated by Django 4.2.4 on 2024-06-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrative', '0004_rename_adminid1_admin_adminid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustInfo',
        ),
    ]
